# Generated by Django 3.2.7 on 2022-11-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_of_review',
            field=models.IntegerField(default=0, verbose_name='レビュー投稿数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_of_word',
            field=models.IntegerField(default=0, verbose_name='口コミ投稿数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_address',
            field=models.CharField(blank=True, choices=[('kanto', '関東'), ('kansai', '関西'), ('other', 'その他')], max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('man', '男性'), ('woman', '女性')], max_length=5, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='名無し', max_length=120, verbose_name='ユーザー名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
    ]
