# Generated by Django 3.2.7 on 2022-11-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221124_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='', max_length=120, verbose_name='ユーザー名'),
        ),
    ]
