# Generated by Django 3.2.7 on 2022-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_address',
            field=models.CharField(blank=True, choices=[('関東', '関東'), ('関西', '関西'), ('その他', 'その他')], max_length=50, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=5, null=True, verbose_name='性別'),
        ),
    ]
