# Generated by Django 3.2.7 on 2023-02-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_birthday_day',
            field=models.DateField(blank=True, choices=[('1日', '1日'), ('2日', '2日'), ('3日', '3日'), ('4日', '4日'), ('5日', '5日'), ('6日', '6日'), ('7日', '7日'), ('8日', '8日'), ('9日', '9日'), ('10日', '10日'), ('11日', '11日'), ('12日', '12日'), ('13日', '13日'), ('14日', '14日'), ('15日', '15日'), ('16日', '16日'), ('17日', '17日'), ('18日', '18日'), ('19日', '19日'), ('20日', '20日'), ('21日', '21日'), ('22日', '22日'), ('23日', '23日'), ('24日', '24日'), ('25日', '25日'), ('26日', '26日'), ('27日', '27日'), ('28日', '28日'), ('29日', '29日'), ('30日', '30日'), ('31日', '31日')], null=True, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_birthday_month',
            field=models.DateField(blank=True, choices=[('1月', '1月'), ('2月', '2月'), ('3月', '3月'), ('4月', '4月'), ('5月', '5月'), ('6月', '6月'), ('7月', '7月'), ('8月', '8月'), ('9月', '9月'), ('10月', '10月'), ('11月', '11月'), ('12月', '12月')], null=True, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(blank=True, choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010')], null=True, verbose_name='年'),
        ),
    ]
