# Generated by Django 3.2.7 on 2023-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230213_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_birthday_day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_birthday_month',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
    ]
