# Generated by Django 3.2.7 on 2022-11-14 03:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='カテゴリー')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='商品名')),
                ('description', models.TextField(max_length=500, verbose_name='詳細')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3')),
                ('price1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Amazon価格')),
                ('link1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Amazon店舗に飛ぶ')),
                ('price2', models.CharField(blank=True, max_length=40, null=True, verbose_name='楽天価格')),
                ('link2', models.CharField(blank=True, max_length=500, null=True, verbose_name='楽天店舗に飛ぶ')),
                ('price3', models.CharField(blank=True, max_length=40, null=True, verbose_name='Yahooショッピング価格')),
                ('link3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yahooショッピング店舗に飛ぶ')),
                ('rating', models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='商品評価')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_brand', models.TextField(blank=True, null=True, verbose_name='商品ブランド')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.category', verbose_name='カテゴリー')),
                ('like_product', models.ManyToManyField(related_name='product_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
    ]
