# Generated by Django 3.2.7 on 2022-11-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.CharField(blank=True, default=0, max_length=40, null=True, verbose_name='Amazon価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.CharField(blank=True, default=0, max_length=40, null=True, verbose_name='楽天価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price3',
            field=models.CharField(blank=True, default=0, max_length=40, null=True, verbose_name='Yahooショッピング価格'),
        ),
    ]
