# Generated by Django 3.2.7 on 2022-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221116_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, verbose_name='Amazon価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, verbose_name='楽天価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True, verbose_name='Yahooショッピング価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='商品名'),
        ),
    ]
