# Generated by Django 3.2.7 on 2023-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230201_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='楽天店舗に飛ぶ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amazon店舗に飛ぶ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='楽天価格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Amazon価格'),
        ),
    ]
