# Generated by Django 3.2.7 on 2022-11-11 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordID', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='口コミID')),
                ('review_title', models.CharField(max_length=100, verbose_name='口コミタイトル')),
                ('review_text', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('created_by', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name_plural': 'project',
            },
        ),
    ]
