# Generated by Django 3.2.7 on 2022-11-16 02:24

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_name_category_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recently_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visited', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('productID', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='商品ID')),
                ('userID', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=100, verbose_name='レビュータイトル')),
                ('review_text', models.TextField(blank=True, max_length=250, null=True, verbose_name='レビュー内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('productID', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='商品ID')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.UUIDField(editable=False, verbose_name=accounts.models.CustomUser)),
                ('wished_item', models.UUIDField(editable=False, verbose_name=shop.models.Product)),
                ('slug', models.SlugField(verbose_name='管理番号')),
                ('added_date', models.DateTimeField(auto_now=True, verbose_name='追加された日時')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
