# Generated by Django 4.1.2 on 2023-01-25 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordID', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ワードID')),
                ('word_title', models.CharField(max_length=100, verbose_name='口コミタイトル')),
                ('word_text', models.TextField(blank=True, max_length=250, null=True, verbose_name='口コミ内容')),
                ('word_created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('word_updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('word_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('word_created_by', models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name_plural': 'Word',
            },
        ),
    ]
