# Generated by Django 3.2.7 on 2023-01-26 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221117_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20230125_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Review'},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='userID1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_item1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='word',
            name='like_word',
            field=models.ManyToManyField(default=0, related_name='like_word', to=settings.AUTH_USER_MODEL, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='管理番号'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
