# Generated by Django 3.2.7 on 2023-01-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230126_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_item',
        ),
    ]
