# Generated by Django 3.2.7 on 2023-01-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230126_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='userID1',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_item1',
            new_name='wished_item',
        ),
    ]
