# Generated by Django 3.2.7 on 2023-01-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20230126_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
    ]
