# Generated by Django 3.2.7 on 2023-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_wishlist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(auto_now=True, verbose_name='追加された日時'),
        ),
    ]
