# Generated by Django 3.2.7 on 2023-01-27 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_wishlist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_review',
            field=models.ManyToManyField(default=0, related_name='like_review', to=settings.AUTH_USER_MODEL, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='review_created_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='word_created_by', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
