# Generated by Django 3.2.7 on 2022-12-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='userID',
        ),
    ]
