# Generated by Django 3.2.7 on 2022-12-02 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_wishlist_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wished_item',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='商品ID'),
        ),
    ]
