# Generated by Django 3.2.7 on 2023-02-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_word_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
